-- 1. 清理舊資料
DROP VIEW IF EXISTS view_post_details CASCADE;
DROP TABLE IF EXISTS post_tag_relation CASCADE;
DROP TABLE IF EXISTS tags CASCADE;
DROP TABLE IF EXISTS comments CASCADE;
DROP TABLE IF EXISTS posts CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS profiles CASCADE;

-- 2. 建立 Profiles (關聯 Supabase Auth)
CREATE TABLE profiles (
    id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    avatar_url TEXT,
    bio TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. 分類表
CREATE TABLE categories (
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    slug TEXT UNIQUE NOT NULL,
    description TEXT
);

-- 4. 文章表 (注意 author_id 是 UUID)
CREATE TABLE posts (
    post_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
    category_id BIGINT REFERENCES categories(category_id) ON DELETE SET NULL,
    title TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    content TEXT NOT NULL,
    status TEXT DEFAULT 'published' CHECK (status IN ('draft', 'published', 'archived')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. 標籤與關聯表
CREATE TABLE tags (
    tag_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL
);

CREATE TABLE post_tag_relation (
    post_id BIGINT REFERENCES posts(post_id) ON DELETE CASCADE,
    tag_id BIGINT REFERENCES tags(tag_id) ON DELETE CASCADE,
    PRIMARY KEY (post_id, tag_id)
);

-- 6. 啟用 RLS 與 設定政策
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE posts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read on profiles" ON profiles FOR SELECT USING (true);
CREATE POLICY "Allow public read on categories" ON categories FOR SELECT USING (true);
CREATE POLICY "Allow public read on posts" ON posts FOR SELECT USING (true);

-- 7. 建立視圖 (View)
CREATE VIEW view_post_details AS
SELECT 
    p.post_id, p.title, p.slug, p.status, p.created_at,
    u.username AS author_name,
    c.name AS category_name
FROM posts p
JOIN profiles u ON p.author_id = u.id
LEFT JOIN categories c ON p.category_id = c.category_id;

-- 8. 插入初始化基礎資料
INSERT INTO categories (name, slug) VALUES 
('程式開發', 'programming'), 
('人工智慧', 'ai'), 
('科技生活', 'tech-life');

INSERT INTO tags (name) VALUES ('SQL'), ('Next.js'), ('Supabase');
